version: 2.1
commands: 
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install
  makedir:
    steps:
      - run:
          name: Make Directory for Output
          command: |
            cd src 
            mkdir junit
            ls
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - makedir
      - run:
          name: unit testing
          command: |
            cd src
            npm run test-unit
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: src/junit
      - store_artifacts:
          path: src/junit

workflows:
  version: 2
  build-test-package:
    jobs:
      - build