version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install

#Make a job 'build' with unit testing, lint test and test coverage that store it as artifacts.
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
          #Unit testing
          name: Unit testing
          command: |
            cd src
            mkdir junit
            npm run test-unit
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: src/junit
      - store_artifacts:
          path: src/junit
      - run:
          #Lint test
          name: Lint testing
          command: |
            cd src
            npm run test-lint
          environment:
            MOCHA_FILE: eslint.xml
          when: always
      - store_artifacts:
          path: src/eslint.xml
      - run:
          #Test coverage
          name: Test code coverage
          command: |
            cd src
            mkdir coverage
            npm run test-coverage
          when: always
      - store_artifacts:
          path: src/coverage/lcov.info
          #Pack artifacts

  #Create job packaging to package artifacts
  packaging:
    docker:
      - image: circleci/node:lts
        environment:
          NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run:
          name: Packing artifacts
          command: |
            cd src
            npm pack
      - store_artifacts:
          path: src/rmit-app-0.0.0.tgz

  #Create integration test job
  test-integration:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: servian
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - install_deps
      - run:
          name: Integration test
          command: |
            cd src
            mkdir integrationtest
            npm run test-integration
          when: always
      - store_test_results:
          path: src/integrationtest
      - store_artifacts:
          path: src/integrationtest
  test-e2e:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: servian
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - install_deps
      - run:
          name: test e2e
          command: |
            cd src
            npm run start:prod & 
            npx wait-on http://localhost:3000
            npm run test-e2e
          environment:
            QAW_HEADLESS: "TRUE"
            QAW_ARTIFACT_PATH: src/,qawolf
      - store_artifacts:
          path: src/.qawolf
      

        
workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - packaging
      - test-integration
      - test-e2e:
          requires:
            - test-integration
