version: 2.1
commands: 
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install
  makedir:
    steps:
      - run:
          name: Make Directory for Output
          command: |
            cd src 
            mkdir junit
            ls

#Make a job 'build' with unit testing, lint test and test coverage that store it as artifacts.
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - makedir
      - run: 
          #Unit testing
          name: Unit testing
          command: |
            cd src
            npm run test-unit
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: src/junit
      - store_artifacts:
          path: src/junit
      - run:
          #Lint test
          name: Lint testing
          command: |
            cd src
            npm run test-lint
          environment:
            MOCHA_FILE: eslint.xml
          when: always
      - store_artifacts:
          path: src/eslint.xml
      - run:
          #Test coverage
          name: Test code coverage
          command: | 
            cd src
            mkdir coverage
            npm run test-coverage
          when: always
      - store_artifacts:
          path: src/coverage/lcov.info

#Make a packaging job to pack artifacts and store it
  packaging:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
          name: Packing artifacts
          command:  |
            cd src
            npm pack
      - store_artifacts:
          path: src/rmit-app-0.0.0.tgz

  test-integration:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - intsall_deps
      - run:
          name: Integration test
          command: |
            cd src
            npm run test-integration

workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - packaging:
          requires:
            - build