version: 2.1
commands: 
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install
  makedir:
    steps:
      - run:
          name: Make Directory for Output
          command: |
            cd src 
            mkdir junit
            ls
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - makedir
      - run:
          name: Unit testing
          command: |
            cd src
            npm run test-unit
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: src/junit
      - store_artifacts:
          path: src/junit
      - run:
          name: Lint testing
          command: |
            cd src
            npm run test-lint
          environment:
            MOCHA_FILE: lint-test-results.xml
          when: always
      - store_artifacts:
          path: src/lint-test-results.xml
      - run:
          name: Test code coverage
          command: | 
            cd src
            mkdir coverage
            npm run test-coverage
      - store_artifacts:
          path: src/coverage/lcov.info
      - run:
          name: check coverage Directory
          command: |
            cd src
            cd coverage
            ls

workflows:
  version: 2
  build-test-package:
    jobs:
      - build